Adjust strncpy call to not use string length
Gcc doesn't like this:
dbxread.c:66:5: error: ‘strncpy’ output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
     strncpy(s + n, c, l);
     ^~~~~~~~~~~~~~~~~~~~
dbxread.c:64:9: note: length computed here
     l = strlen(c);
         ^~~~~~~~~
cc1: all warnings being treated as errors

Actually the code was OK, but it's nicer to use memcpy() to make it clear
that we don't want the NUL terminator to be copied.

A different bug is corrected: the array c was not initialized, so if a
string shorter than 255 bytes was read, and a NUL byte was was not
present in the bytes read, strlen() would read garbage data from the
heap, in the area between the data read and the 255th byte which was
initalized to NUL.